### ISSUE TITLE
Running REST service and admin endpoint on the same port

### ISSUE THREAD

**Issue by scf37** [twitter/twitter-server#40] opened 2016-05-16 11:26 UTC
Why:
- less ports to allocate and remember if running REST service. Every java application has two ports exposed (JMX and HTTP). Having three (JMX, HTTP, HTTP admin) seems like overkill

Problem:
- AdminHttpServer is not configurable and is not really suited for production use. E.g. it overwrites 404 responses, has stats collection disabled, uses hardcoded 404 handler.

Solution:
Let client obtain instance of `localMuxer` from `AdminHttpServer.updateMuxer()`

That's how I have to do right now:
```
class X extends  com.twitter.app.App with AdminHttpServer with Admin {
    val allRoutes = routes
    //copy-pasted from AdminHttpServer.updateMuxer
    //with additional hacks to access package-protected ServerRegistry and ClientRegistry
    //it returns instance of localMuxer, i.e. Service that serves /admin endpoint
    def updateMuxer(): Service[Request, Response] = { ..... }
}
```

Also, `ServerAdmissionControl` is package-protected. Is that intentional?

Twitter-server 1.19.0
Finagle 6.34.0
Scala 2.11.7

**Comment by mosesn** [comment] 2016-05-24 14:34
@scf37 could you elaborate on the problem you're trying to solve?  Are you in a port-constrained environment?

In general, it seems a little dangerous to me to expose regular endpoints at the same place as the admin endpoint.  For example, if someone gets access to make requests to your machine, they now have the ability to also shut it down.  You can't have different firewall rules for the admin endpoint, and it will be difficult to add authorization just to the admin endpoints (it doesn't exist yet, but we're planning on providing something like kerberos support for the admin endpoint).

In general, our experience is that it's not very expensive to spend another port, so our preference is to separate church and state.

I don't think we had a use case for making `ServerAdmissionControl` public, but if you have an idea in mind, we'd be happy to accept a PR!

**Comment by scf37** [comment] 2016-05-24 15:07
Hi, thanks for response.

Problem we are solving is just cutting down number of ports to remember for each application - i.e. usability issue, not performance or resource consumption one. AFAIK you mainly use binary protocols like `Thrift` and `Mux` so you have to use different ports for admin and main service.

We use finagle apps behind `nginx` for load balancing, ddos protection and general shielding from outside world so covering /admin to be inaccessible from external addresses is not a problem. Services not intended to be visible from outside are in private subnet so for them it is not an issue as well.

I'm not yet sure what `ServerAdmissionControl` do, I just wanted to manually construct HTTP server to be "the same as twitter admin uses".

As for authorization, hack mentioned in OP allows to add authorization to `/admin` by simply adding filters on top of `/admin` service.

I'd really like to provide PR that separates `/admin` service construction from admin HTTP server construction but do not really know how - it is quite complicated code down there + I do not know whether you are using that `Route`/`IndexView` mechanism internally.

**Comment by mosesn** [comment] 2016-05-24 16:13
Hmm, so it seems like the problem is that it's difficult to hold all three port numbers in your head?  Are they the same on every machine?  How do you collocate processes?  Maybe there's a better system than trying to remember all of the ports.  Could you put your port numbers in a runbook?

**Comment by scf37** [comment] 2016-05-24 16:30
Well, it is surely not a major issue :-) Of course ports are known and documented and also can be viewed in our service discovery service. It is just inconvenient to have more open ports.

We have multiple services, every with different ports assigned by default so they could be run on the same host (e.g. dev machine) w/o additional configuration.

I just feel that "lets see admin page for node xxx of application yyy" should be easier than going to the wiki and looking up hosts and ports there. Less ports = less work -> wiki -> work roundtrips.

How do you perform that ""lets see admin page for node xxx of application yyy" task? At your scale, it must be documentation or query to service discovery.

**Comment by mosesn** [comment] 2016-05-24 17:00
We have too many services to say every service gets different ports, and we might want to run the same service more than once on the same machine, so our mesos scheduler assigns ports to a service.  When we want to look up an instance of a service, we need to look up which host it has been scheduled on too, so we grab the port information with it.

**Comment by mosesn** [comment] 2016-05-29 03:14
I don't think that using the TwitterServer admin endpoint as your main http server is the right solution.  I'm going to close this issue, but if you want to revisit it, please reopen it!

**Closed by mosesn** 2016-05-29 03:14 UTC
